[package]
name = "surreal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raphtory = "0.7.0"
serde_json = "1.0.111"
surrealdb = { version = "1.1.1", features = ["kv-rocksdb"] }
tokio = "1.35.1"
