name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: rust-rustfmt-check
      # You may pin to the exact commit or the version.
      # uses: mbrobbel/rustfmt-check@d8a22d8a78264c51e7439cc9a2d9f607cc8be328
      uses: mbrobbel/rustfmt-check@0.8.0
      with:
        # Output mode (commit or review)
        mode: review # optional, default is commit
