name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        rustup toolchain install nightly
        cargo install wasm-tools
        rustup target add wasm32-wasi
        rustup target add wasm32-wasi --toolchain nightly
        cargo install cargo-wasi
        cargo +nightly build
    - name: Lint
      uses: wearerequired/lint-action@v2.3.0
